// File generated by FlutterFire CLI.
// NOTE: Run `flutterfire configure` to regenerate this file with your project settings.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR_WEB_API_KEY',
    appId: 'YOUR_WEB_APP_ID',
    messagingSenderId: '241917597382',
    projectId: 'truepay-72060',
    authDomain: 'truepay-72060.firebaseapp.com',
    databaseURL: 'https://truepay-72060-default-rtdb.firebaseio.com',
    storageBucket: 'truepay-72060.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbkhQZp_sbiGsaWYsqUqdJErvFVnI-KBI',
    appId: '1:241917597382:android:11278578d75ad12f4969c7',
    messagingSenderId: '241917597382',
    projectId: 'truepay-72060',
    databaseURL: 'https://truepay-72060-default-rtdb.firebaseio.com',
    storageBucket: 'truepay-72060.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGgjQjuHGrj7vJi3cfunpDm7fxN9OEiJg',
    appId: '1:241917597382:ios:bc9a8f15945303584969c7',
    messagingSenderId: '241917597382',
    projectId: 'truepay-72060',
    databaseURL: 'https://truepay-72060-default-rtdb.firebaseio.com',
    storageBucket: 'truepay-72060.firebasestorage.app',
    iosBundleId: 'com.example.TP',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGgjQjuHGrj7vJi3cfunpDm7fxN9OEiJg',
    appId: '1:241917597382:ios:bc9a8f15945303584969c7',
    messagingSenderId: '241917597382',
    projectId: 'truepay-72060',
    databaseURL: 'https://truepay-72060-default-rtdb.firebaseio.com',
    storageBucket: 'truepay-72060.firebasestorage.app',
    iosBundleId: 'com.example.TP',
  );
}

