# Uncomment this line to define a global platform for your project
platform :ios, '13.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    # Xcode 16+ clang rejects -GCC_WARN_INHIBIT_ALL_WARNINGS (parsed as invalid -G).
    # See https://github.com/grpc/grpc/issues/36888
    if target.name == 'BoringSSL-GRPC'
      target.source_build_phase.files.each do |file|
        next unless file.settings && file.settings['COMPILER_FLAGS']

        flags = file.settings['COMPILER_FLAGS'].split
        flags.reject! { |f| f == '-GCC_WARN_INHIBIT_ALL_WARNINGS' }
        file.settings['COMPILER_FLAGS'] = flags.join(' ')
      end
    end
    flutter_additional_ios_build_settings(target)
  end

  # Xcode 16.3+ Clang requires an explicit empty template argument list here.
  # https://github.com/grpc/grpc/issues/39364
  %w[gRPC-Core gRPC-C++].each do |pod|
    basic_seq = File.join(installer.sandbox.root, "#{pod}/src/core/lib/promise/detail/basic_seq.h")
    next unless File.exist?(basic_seq)

    File.chmod(0o644, basic_seq)
    contents = File.read(basic_seq)
    fixed = contents.gsub(
      'Traits::template CallSeqFactory(f_, *cur_, std::move(arg))',
      'Traits::template CallSeqFactory<>(f_, *cur_, std::move(arg))'
    )
    File.write(basic_seq, fixed) if fixed != contents
  end
end
